### ISSUE TITLE
NPM cli module cannot be found

### ISSUE THREAD

**Issue by henryruhs** [yohang/dependency-tools#2]
![npm-cli-issue](https://f.cloud.github.com/assets/1835397/1233866/03a23844-2948-11e3-9a05-b16fd2fb6a49.png)

Please read the screenshot, maybe just a issue under Windows?

Similar to: http://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows

**Comment by henryruhs** [comment]
Btw: running npm install is working fine... I tried to google for the solution but found nothing...

![npm-cli-issue2](https://f.cloud.github.com/assets/1835397/1234002/5a2c2a76-2952-11e3-809d-4b0545cfe530.png)

**Comment by henryruhs** [comment]
A stupid "shell_exec" call over Symfony's ProcessBuilder worked...^^ but thats just a hint

**Comment by yohang** [comment]
I'm aware of this issue on windows, i'll find a fix soon... Without dropping Symfony Process ;)

**Comment by henryruhs** [comment]
sure, i just wanted to point out the source of problem

**Comment by Nek-** [comment]
@yohang woo ! You have an idea about fixing the issue without dropping Symfony Process ?!

**Comment by yohang** [comment]
On windows ?

**Comment by Nek-** [comment]
Yes

**Comment by yohang** [comment]
Well, i'm aware of this... Si i think i have to run a VM to fix that shit ;)

**Comment by Nek-** [comment]
Probably yes. I've no idea what's wrong and i don't know why i can't debug
it easily... (when i remove an entire class everything continue like if
there is hard apc cache.. but there is not...)

Windows! T_T

Notice that `system ('npm install')` work very well.

**Comment by henryruhs** [comment]
I guess / vs. \

**Comment by Nek-** [comment]
I do not see the connection with the problem we have.

**Comment by yohang** [comment]
Fixed ec7fe092743720de22633f56281536e8d258982e, can you test that ?

**Comment by Nek-** [comment]
Nice, works for simple commands (I mean `npm` or `bower`).

But with a configuration like that in the composer.json, it doesn't work:

``` json
{
    "extra": {
        "dependency-tools": {
            "npm":   true,
            "bower": {
                "path": "./node_modules/bower/bin/bower"
            }
        }
    }
}
```

![screenshot at 2013-12-20 10 06 35](https://f.cloud.github.com/assets/972456/1789367/33b6f99a-6956-11e3-9c1a-db5dd1d7ecc5.png)

A solution can be adding the "node" command in front of the command... Maybe by signaling it as option ? "use_node" or "execute_with"

**Comment by Nek-** [comment]
Here is a solution working:

``` php
<?php

    /**
     * @param array  $args
     * @param string $ifError
     * @throws \RuntimeException
     */
    protected static function execCommand($options, $cmd, array $args, $ifError)
    {
        $executableFinder = new ExecutableFinder;
        if (is_array($options)) {
            if (isset($options['execute_with'])) {
                $cmd = $executableFinder->find($options['execute_with']);
                if (isset($options['path'])) {
                    array_unshift($args, $options['path']);
                }
            } else if (isset($options['path'])) {
                $cmd = $options['path'];
            }
        } else {
            $cmd = $executableFinder->find($cmd);
        }


        $out = '';
        $process = ProcessBuilder::create(array_merge(array($cmd), $args))->getProcess();
        $process->run(function($type, $buffer) use (&$out) { $out .= $buffer; });

        if (!$process->isSuccessful()) {
            throw new \RuntimeException($ifError."\n\n".$out);
        }
    }
```

And here is the configuration:

``` json
{
    "extra": {
        "dependency-tools": {
            "npm":   true,
            "bower": {
                "path": "./node_modules/bower/bin/bower",
                "execute_with": "node"
            }
        }
    }
}
```

**Comment by Nek-** [comment]
@yohang what do you think about ? (I know it's ugly and probably need to be separate in serveral classes but don't know how you want to do)

**Comment by henryruhs** [comment]
No solution after 5 years - project seems to be dead anyway...
